pipeline {
    agent {
        label 'java17'
    }
    stages {
        stage("Checkout") {
            steps {
                git url: 'https://github.com/StarJins/calculator.git', branch: 'main'
            }
        }
        stage("Compile") {
            steps {
                sh "./gradlew compileJava"
            }
        }
        stage("Unit test") {
            steps {
                sh "./gradlew test"
            }
        }
    }
}